### ISSUE TITLE
RTE improvements

### ISSUE THREAD

**Issue by sangameshsomawar** [bigbinary/neeto-ui-rn#473]
1. Copy-paste popup is on top of the rich text editor toolbar.
2. Rich text editor is not showing in bold highlighted on click of bold.
3. Add a new prop to show the border.
4. Add a new prop to show an error message.

**Comment by chiragbhaiji** [comment]
@sangameshsomawar

> Rich text editor is not showing in bold highlighted on click of bold.

It was happening because of the missing value for prop `selectedIconTint`. I've set it to `theme.buttons.solid.backgroundColor` as its default value now, so it takes the primary action color from the theme if not provided.

![RTE-highlighted-action](https://user-images.githubusercontent.com/27726339/201978266-5b479d98-a363-4c40-b0e8-0c83eb18191e.png)

Let me know if you have any concerns with the color to be used in this case.

**Comment by sangameshsomawar** [comment]
@chiragbhaiji Yes this will work. Thank you.

**Comment by sangameshsomawar** [comment]
@chiragbhaiji : Closing this issue as we will be using normal text input.
